KAFKA_HOSTS = ['localhost:29092']

KAFKA_INCOMING_TOPIC = 'demo.scraped_firehose'
KAFKA_GROUP = 'demo-group'
KAFKA_CONSUMER_TIMEOUT = 50
KAFKA_CONSUMER_AUTO_OFFSET_RESET = 'latest'
KAFKA_CONSUMER_COMMIT_INTERVAL_MS = 5000
KAFKA_CONSUMER_AUTO_COMMIT_ENABLE = True

SLEEP_TIME = 0.01